import {
  UserProfile,
  EventItem,
  JobListing,
  InterestGroup,
  AppNotification,
  Conversation,
  MentorshipRequest,
  ReferralRequest,
  CampusAnnouncement,
} from './types';

export const MOCK_USERS: UserProfile[] = [
  {
    id: 'user-sarah',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@alumni.univ.edu',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    role: 'alumni',
    verified: true,
    headline: 'Senior Product Manager @ Google | Tech Mentor & Speaker',
    bio: 'Passionate about building scalable AI products and empowering the next generation of tech leaders. Graduated class of 2018 in Computer Science. Happy to offer career guidance, resume reviews, and product strategy advice.',
    education: {
      institution: 'State University of Technology',
      degree: 'B.S.',
      major: 'Computer Science',
      gradYear: 2018,
    },
    currentCompany: 'Google',
    currentRole: 'Senior Product Manager',
    industry: 'Technology & AI',
    location: 'Mountain View, CA',
    distanceMiles: 4.2,
    skills: ['Product Strategy', 'Machine Learning', 'A/B Testing', 'Leadership', 'System Design'],
    interests: ['Artificial Intelligence', 'Mentorship', 'Angel Investing', 'Trail Running'],
    linkedinUrl: 'https://linkedin.com/in/sarah-jenkins',
    githubUrl: 'https://github.com/sarahjenkins',
    portfolioUrl: 'https://sarahjenkins.dev',
    resumeUrl: 'https://alumni.univ.edu/resumes/sarah_jenkins_cv.pdf',
    isMentor: true,
    isMentee: false,
    mentorshipCapacity: 3,
    activeMenteesCount: 1,
    mentorshipBio: 'Offering 1:1 monthly coaching for students interested in breaking into big tech product management and engineering leadership.',
    mentorshipGoals: ['Resume & Interview Prep', 'Navigating Big Tech', 'Transitioning from Eng to PM'],
    visibility: {
      email: 'alumni-only',
      phone: 'hidden',
      location: 'public',
      careerHistory: 'public',
      resume: 'alumni-only',
    },
    profileCompletionPercentage: 100,
  },
  {
    id: 'user-alex',
    name: 'Alex Rivera',
    email: 'alex.rivera@student.univ.edu',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
    role: 'student',
    verified: true,
    headline: 'Computer Science Junior @ Univ | Aspiring ML Engineer',
    bio: 'Junior studying CS and Applied Math. President of the University AI Society. Looking for mentorship in distributed systems and large language model deployment.',
    education: {
      institution: 'State University of Technology',
      degree: 'B.S. Candidate',
      major: 'Computer Science',
      gradYear: 2027,
    },
    currentCompany: 'Univ AI Lab',
    currentRole: 'Undergraduate Researcher',
    industry: 'Technology & AI',
    location: 'San Jose, CA',
    distanceMiles: 12.0,
    skills: ['Python', 'PyTorch', 'React Native', 'C++', 'Algorithms'],
    interests: ['Open Source', 'Hackathons', 'Robotics', 'Basketball'],
    linkedinUrl: 'https://linkedin.com/in/alex-rivera-student',
    githubUrl: 'https://github.com/alexrivera-tech',
    isMentor: false,
    isMentee: true,
    mentorshipCapacity: 1,
    activeMenteesCount: 0,
    mentorshipBio: 'Seeking guidance from alumni working on production ML systems and software engineering interviews.',
    mentorshipGoals: ['Software Engineering Internships', 'Graduate School Advice', 'System Architecture'],
    visibility: {
      email: 'public',
      phone: 'hidden',
      location: 'public',
      careerHistory: 'public',
      resume: 'public',
    },
    profileCompletionPercentage: 92,
  },
  {
    id: 'user-dean',
    name: 'Dean Marcus Cole',
    email: 'marcus.cole@univ.edu',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    role: 'staff',
    verified: true,
    headline: 'Dean of Alumni Relations & University Advancement',
    bio: 'Dedicated to fostering lifelong connections between our global alumni body of 85,000+ graduates and our current academic community.',
    education: {
      institution: 'State University of Technology',
      degree: 'Ph.D.',
      major: 'Educational Leadership & Public Policy',
      gradYear: 2002,
    },
    currentCompany: 'State University',
    currentRole: 'Dean of Alumni Relations',
    industry: 'Higher Education & Philanthropy',
    location: 'San Francisco, CA',
    distanceMiles: 28.5,
    skills: ['Strategic Partnerships', 'Higher Ed Administration', 'Endowment Stewardship', 'Public Speaking'],
    interests: ['University Heritage', 'Student Scholarships', 'Global Summits', 'Classical Music'],
    isMentor: true,
    isMentee: false,
    mentorshipCapacity: 5,
    activeMenteesCount: 2,
    mentorshipBio: 'Connecting ambitious scholars with university leadership and high-impact fellowship opportunities.',
    mentorshipGoals: ['Academic & Policy Careers', 'Non-profit Leadership', 'Public Sector Fellowships'],
    visibility: {
      email: 'public',
      phone: 'public',
      location: 'public',
      careerHistory: 'public',
      resume: 'public',
    },
    profileCompletionPercentage: 100,
  },
  {
    id: 'user-priya',
    name: 'Priya Sharma',
    email: 'priya.sharma@stripe.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    role: 'alumni',
    verified: true,
    headline: 'Staff Software Architect @ Stripe | FinTech & Distributed Systems',
    bio: 'Class of 2015. Architecting payment rails processing billions daily. Avid mentor for women in engineering and open source contributor.',
    education: {
      institution: 'State University of Technology',
      degree: 'M.S.',
      major: 'Software Engineering',
      gradYear: 2015,
    },
    currentCompany: 'Stripe',
    currentRole: 'Staff Software Architect',
    industry: 'FinTech & Payments',
    location: 'San Francisco, CA',
    distanceMiles: 31.0,
    skills: ['Distributed Systems', 'Kafka', 'Go', 'High Availability', 'Architecture Review'],
    interests: ['FinTech', 'Mentoring Women in STEM', 'Cycling', 'Specialty Coffee'],
    linkedinUrl: 'https://linkedin.com/in/priyasharma-tech',
    isMentor: true,
    isMentee: false,
    mentorshipCapacity: 2,
    activeMenteesCount: 1,
    mentorshipBio: 'Mentoring engineers aiming for senior and staff level technical tracks.',
    mentorshipGoals: ['Technical Design', 'System Architecture', 'Career Leveling'],
    visibility: {
      email: 'alumni-only',
      phone: 'hidden',
      location: 'public',
      careerHistory: 'public',
      resume: 'alumni-only',
    },
    profileCompletionPercentage: 95,
  },
  {
    id: 'user-david',
    name: 'David Chen',
    email: 'david.chen@sequoiacap.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    role: 'alumni',
    verified: true,
    headline: 'Partner @ Sequoia Capital | Early-Stage Enterprise Software',
    bio: 'B.S. in Electrical Eng & Finance (2012). Partner focused on cloud infrastructure, cybersecurity, and applied AI startups.',
    education: {
      institution: 'State University of Technology',
      degree: 'B.S.',
      major: 'Electrical Engineering & Finance',
      gradYear: 2012,
    },
    currentCompany: 'Sequoia Capital',
    currentRole: 'Partner',
    industry: 'Venture Capital & Private Equity',
    location: 'Menlo Park, CA',
    distanceMiles: 8.5,
    skills: ['Venture Capital', 'Startup Due Diligence', 'Fundraising', 'B2B SaaS'],
    interests: ['Venture Investing', 'Deep Tech', 'Marathons', 'Wine Collecting'],
    linkedinUrl: 'https://linkedin.com/in/davidchen-vc',
    isMentor: true,
    isMentee: false,
    mentorshipCapacity: 2,
    activeMenteesCount: 2,
    mentorshipBio: 'Mentoring student and alumni founders raising pre-seed and seed rounds.',
    mentorshipGoals: ['Startup Pitching', 'Fundraising Strategy', 'Product-Market Fit'],
    visibility: {
      email: 'alumni-only',
      phone: 'hidden',
      location: 'public',
      careerHistory: 'public',
      resume: 'hidden',
    },
    profileCompletionPercentage: 96,
  },
  {
    id: 'user-elena',
    name: 'Dr. Elena Rostova',
    email: 'elena.rostova@mayoclinic.org',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=300&q=80',
    role: 'alumni',
    verified: true,
    headline: 'Director of Computational Biology @ Mayo Clinic',
    bio: 'Class of 2014 (Bioengineering). Working on AI-driven precision therapeutics and genomics diagnostics.',
    education: {
      institution: 'State University of Technology',
      degree: 'Ph.D.',
      major: 'Bioengineering & Bioinformatics',
      gradYear: 2014,
    },
    currentCompany: 'Mayo Clinic',
    currentRole: 'Director of Computational Biology',
    industry: 'Healthcare & Biotech',
    location: 'Palo Alto, CA',
    distanceMiles: 6.1,
    skills: ['Bioinformatics', 'Genomics', 'Clinical Trials', 'Data Science', 'Python'],
    interests: ['Precision Medicine', 'HealthTech', 'Violin', 'Hiking'],
    isMentor: true,
    isMentee: false,
    mentorshipCapacity: 3,
    activeMenteesCount: 0,
    mentorshipBio: 'Guiding pre-med and biotech students interested in computational health careers.',
    mentorshipGoals: ['Biotech Research', 'Industry vs Academic Paths', 'Ph.D. Advice'],
    visibility: {
      email: 'public',
      phone: 'hidden',
      location: 'public',
      careerHistory: 'public',
      resume: 'public',
    },
    profileCompletionPercentage: 100,
  }
];

export const MOCK_EVENTS: EventItem[] = [
  {
    id: 'event-1',
    title: 'Global Alumni Reunion 2026: Gala & Innovation Showcase',
    description: 'Join over 1,200 alumni and distinguished faculty for the annual homecoming celebration! Featuring keynote addresses by top industry founders, student project demos, banquet dinner, and networking cocktails.',
    category: 'reunion',
    type: 'hybrid',
    date: 'Oct 16 - 18, 2026',
    time: '5:30 PM - 10:00 PM PST',
    location: 'University Grand Auditorium & Online Live Stream',
    virtualLink: 'https://univ.edu/live/alumni-gala-2026',
    organizer: 'Office of Alumni Relations',
    capacity: 500,
    rsvpCount: 442,
    isRsvpd: true,
    isWaitlisted: false,
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=600&q=80',
    ],
    feedbackGiven: false,
  },
  {
    id: 'event-2',
    title: 'Silicon Valley Alumni Tech Mixer: Generative AI & Robotics',
    description: 'An evening of informal networking, lightning talks, and drinks hosted at Google Cloud Campus for alumni founders, engineers, and researchers.',
    category: 'networking',
    type: 'in-person',
    date: 'Sep 24, 2026',
    time: '6:30 PM - 9:00 PM PST',
    location: 'Google Building MP7, Mountain View, CA',
    organizer: 'Silicon Valley Alumni Chapter',
    capacity: 120,
    rsvpCount: 120,
    isRsvpd: false,
    isWaitlisted: true,
    image: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=800&q=80',
    feedbackGiven: false,
  },
  {
    id: 'event-3',
    title: 'Mastering Technical Interviews & PM Pitching',
    description: 'Hands-on workshop led by senior alumni from Google, Stripe, and Apple. Includes mock technical rounds, resume critiques, and AMA session.',
    category: 'workshop',
    type: 'virtual',
    date: 'Oct 02, 2026',
    time: '11:00 AM - 1:30 PM PST',
    location: 'Zoom Virtual Interactive Classroom',
    virtualLink: 'https://univ.edu/zoom/interview-prep-2026',
    organizer: 'Career Services & Alumni Mentorship Committee',
    capacity: 250,
    rsvpCount: 188,
    isRsvpd: true,
    isWaitlisted: false,
    image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
    feedbackGiven: false,
  },
  {
    id: 'event-4',
    title: 'Healthcare & Biotech Frontiers Panel',
    description: 'Hear from physician-scientists and biotech venture leaders on next-generation clinical diagnostics, FDA pathways, and AI drug discovery.',
    category: 'keynote',
    type: 'in-person',
    date: 'Nov 12, 2026',
    time: '4:00 PM - 7:00 PM PST',
    location: 'Bioengineering Science Center, Room 104',
    organizer: 'Alumni Health Sciences Alliance',
    capacity: 180,
    rsvpCount: 114,
    isRsvpd: false,
    isWaitlisted: false,
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    feedbackGiven: false,
  }
];

export const MOCK_JOBS: JobListing[] = [
  {
    id: 'job-1',
    title: 'Senior Product Manager - Core AI Platforms',
    company: 'Google',
    logo: 'https://www.google.com/favicon.ico',
    location: 'Mountain View, CA (Hybrid)',
    type: 'Full-Time',
    experienceLevel: 'Senior',
    description: 'Lead product vision and developer ergonomics for next-generation Gemini developer integrations and real-time enterprise AI tooling.',
    requirements: [
      '5+ years in Product Management with software/developer platforms',
      'Strong technical background in CS, data structures, or API systems',
      'Demonstrated experience shipping 0-to-1 products with millions of users',
    ],
    salaryRange: '$195,000 - $275,000 + Equity',
    postedDate: '2 days ago',
    applyLink: 'https://careers.google.com/jobs/results/12345',
    postedBy: MOCK_USERS[0], // Sarah Jenkins
    status: 'approved',
    alumniEmployeesCount: 14,
  },
  {
    id: 'job-2',
    title: 'Software Engineer - Payments Infrastructure',
    company: 'Stripe',
    logo: 'https://stripe.com/favicon.ico',
    location: 'San Francisco, CA or Remote',
    type: 'Full-Time',
    experienceLevel: 'Mid-Level',
    description: 'Build fault-tolerant payment pipelines that move billions of dollars securely every single day with sub-second latency.',
    requirements: [
      '3+ years experience with distributed backends (Go, Java, or Rust)',
      'Experience with Kafka, PostgreSQL, high-concurrency systems',
      'BS/MS in Computer Science or equivalent practical experience',
    ],
    salaryRange: '$170,000 - $230,000 + Equity',
    postedDate: '3 days ago',
    applyLink: 'https://stripe.com/jobs/infra-swe',
    postedBy: MOCK_USERS[3], // Priya Sharma
    status: 'approved',
    alumniEmployeesCount: 8,
  },
  {
    id: 'job-3',
    title: 'Machine Learning Research Intern (Summer 2027)',
    company: 'Google',
    logo: 'https://www.google.com/favicon.ico',
    location: 'Sunnyvale, CA (Onsite)',
    type: 'Internship',
    experienceLevel: 'Entry-Level',
    description: 'Work directly with Google Research scientists on novel model evaluation methods, multimodal perception, and efficient inference.',
    requirements: [
      'Currently enrolled in BS, MS, or PhD in Computer Science or related field',
      'Proficiency in Python, PyTorch/JAX',
      'Demonstrated research curiosity, publications, or notable side projects',
    ],
    salaryRange: '$58 - $68 / hour + housing stipend',
    postedDate: '1 week ago',
    applyLink: 'https://careers.google.com/students/internships-swe',
    postedBy: MOCK_USERS[0],
    status: 'approved',
    alumniEmployeesCount: 14,
  },
  {
    id: 'job-4',
    title: 'Venture Capital Associate - Deep Tech & AI',
    company: 'Sequoia Capital',
    logo: 'https://sequoiacap.com/favicon.ico',
    location: 'Menlo Park, CA',
    type: 'Full-Time',
    experienceLevel: 'Mid-Level',
    description: 'Sourcing, due diligence, founder meetings, and financial modeling for breakthrough AI, space-tech, and compute hardware startups.',
    requirements: [
      '2-4 years in software engineering, management consulting, or product',
      'Sharp analytical intuition and strong curiosity for disruptive tech',
      'Undergraduate degree in STEM or Quantitative Economics',
    ],
    salaryRange: '$180,000 - $240,000 + Bonus + Carry',
    postedDate: '4 days ago',
    applyLink: 'https://sequoiacap.com/careers/associate',
    postedBy: MOCK_USERS[4], // David Chen
    status: 'approved',
    alumniEmployeesCount: 3,
  }
];

export const MOCK_GROUPS: InterestGroup[] = [
  {
    id: 'group-tech',
    name: 'Tech Founders & Engineers',
    description: 'Exclusive hub for alumni and students building software, hardware, and scalable technology startups.',
    category: 'Technology',
    iconName: 'code-slash-outline',
    bannerColor: '#1E3A8A',
    membersCount: 1420,
    isMember: true,
    posts: [
      {
        id: 'post-1',
        groupId: 'group-tech',
        author: MOCK_USERS[0], // Sarah Jenkins
        content: 'Excited to announce that Google is opening 2027 technical internship roles early for university partners! Feel free to reach out via DM if you are looking for referrals or guidance on system design interviews.',
        tags: ['Hiring', 'Internships', 'Google'],
        likesCount: 38,
        isLikedByMe: true,
        comments: [
          {
            id: 'comm-1',
            author: MOCK_USERS[1], // Alex Rivera
            content: 'Thank you Sarah! Just sent you a referral request for the ML Research intern role.',
            timestamp: '2 hours ago',
          }
        ],
        timestamp: '4 hours ago',
      },
      {
        id: 'post-2',
        groupId: 'group-tech',
        author: MOCK_USERS[3], // Priya Sharma
        content: 'We just open-sourced our high-throughput payment idempotency library at Stripe! Would love student and alumni feedback on the architecture.',
        tags: ['OpenSource', 'DistributedSystems', 'Stripe'],
        likesCount: 24,
        isLikedByMe: false,
        comments: [],
        timestamp: '1 day ago',
      }
    ]
  },
  {
    id: 'group-vc',
    name: 'Wall Street & Venture Capital',
    description: 'Network for investment banking analysts, private equity partners, venture capitalists, and fintech innovators.',
    category: 'Finance',
    iconName: 'trending-up-outline',
    bannerColor: '#065F46',
    membersCount: 890,
    isMember: true,
    posts: [
      {
        id: 'post-vc-1',
        groupId: 'group-vc',
        author: MOCK_USERS[4], // David Chen
        content: 'Hosting an informal office-hours chat next Tuesday for alumni founders gearing up for Seed/Series A rounds. Drop a comment if interested in an invite!',
        tags: ['OfficeHours', 'Fundraising', 'Sequoia'],
        likesCount: 42,
        isLikedByMe: true,
        comments: [],
        timestamp: '2 days ago',
      }
    ]
  },
  {
    id: 'group-health',
    name: 'Healthcare & Biotech Alliance',
    description: 'Physicians, medical researchers, pharmaceutical specialists, and biomedical engineers.',
    category: 'Healthcare',
    iconName: 'medkit-outline',
    bannerColor: '#0E7490',
    membersCount: 650,
    isMember: false,
    posts: []
  },
  {
    id: 'group-reunion',
    name: 'Class of 2018 Reunion Committee',
    description: 'Official committee channel coordinating travel, accommodations, and reunion events for the 2018 graduating class.',
    category: 'Reunion',
    iconName: 'school-outline',
    bannerColor: '#7C3AED',
    membersCount: 310,
    isMember: false,
    posts: []
  }
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-sarah-alex',
    participant: MOCK_USERS[0], // Sarah Jenkins
    lastMessage: {
      id: 'msg-last-1',
      conversationId: 'conv-sarah-alex',
      senderId: 'user-sarah',
      receiverId: 'user-alex',
      text: 'Hi Alex, I looked over your resume. Your PyTorch projects look great! Let us connect for a 30-min mentor session next Thursday.',
      timestamp: '10:45 AM',
      read: false,
    },
    unreadCount: 1,
    status: 'active',
  },
  {
    id: 'conv-priya-alex',
    participant: MOCK_USERS[3], // Priya Sharma
    lastMessage: {
      id: 'msg-last-2',
      conversationId: 'conv-priya-alex',
      senderId: 'user-alex',
      receiverId: 'user-priya',
      text: 'Thank you Priya for accepting my connection request! I look forward to your talk on distributed systems.',
      timestamp: 'Yesterday',
      read: true,
    },
    unreadCount: 0,
    status: 'active',
  },
  {
    id: 'conv-david-sarah',
    participant: MOCK_USERS[4], // David Chen
    lastMessage: {
      id: 'msg-last-3',
      conversationId: 'conv-david-sarah',
      senderId: 'user-david',
      receiverId: 'user-sarah',
      text: 'Sarah, are you attending the Silicon Valley Tech Mixer next week?',
      timestamp: '3 days ago',
      read: true,
    },
    unreadCount: 0,
    status: 'active',
  }
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    category: 'messages',
    title: 'New Message from Sarah Jenkins',
    message: 'Hi Alex, I looked over your resume. Your PyTorch projects look great!',
    timestamp: '10:45 AM',
    read: false,
    relatedId: 'conv-sarah-alex',
  },
  {
    id: 'notif-2',
    category: 'mentorship',
    title: 'Mentorship Request Accepted',
    message: 'Sarah Jenkins accepted your mentorship request: "Software Engineering & PM Guidance"',
    timestamp: 'Yesterday',
    read: false,
    relatedId: 'user-sarah',
  },
  {
    id: 'notif-3',
    category: 'events',
    title: 'Event Reminder: Silicon Valley Mixer',
    message: 'Silicon Valley Alumni Tech Mixer starts in 48 hours. Check venue details and parking.',
    timestamp: '2 days ago',
    read: true,
    relatedId: 'event-2',
  },
  {
    id: 'notif-4',
    category: 'jobs',
    title: 'Referral Request Submitted',
    message: 'Your referral inquiry for Google ML Research Intern was delivered to Sarah Jenkins.',
    timestamp: '3 days ago',
    read: true,
    relatedId: 'job-3',
  }
];

export const MOCK_MENTORSHIP_REQUESTS: MentorshipRequest[] = [
  {
    id: 'ment-req-1',
    mentorId: 'user-sarah',
    mentor: MOCK_USERS[0],
    menteeId: 'user-alex',
    mentee: MOCK_USERS[1],
    goal: 'Software Engineering Internships & Big Tech PM Transition',
    message: 'Hi Sarah, I am a CS junior leading our campus AI club. I would love your mentorship on preparing for system design interviews and navigating technical internships at Google.',
    status: 'accepted',
    createdAt: '2026-08-20T10:00:00Z',
    scheduledSession: '2026-09-04T17:00:00Z',
  }
];

export const MOCK_REFERRALS: ReferralRequest[] = [
  {
    id: 'ref-1',
    jobId: 'job-3',
    jobTitle: 'Machine Learning Research Intern',
    company: 'Google',
    alumniId: 'user-sarah',
    alumniName: 'Sarah Jenkins',
    requesterId: 'user-alex',
    requesterName: 'Alex Rivera',
    requesterRole: 'Computer Science Junior',
    requesterMajor: 'Computer Science',
    note: 'Hi Sarah, I applied for the ML Research Internship at Google. As a fellow student in our university AI lab, I would be immensely grateful for an internal referral.',
    resumeAttached: true,
    status: 'referred',
    date: 'Aug 27, 2026',
  }
];

export const MOCK_ANNOUNCEMENTS: CampusAnnouncement[] = [
  {
    id: 'ann-1',
    title: '50th Golden Jubilee Homecoming & Global Alumni Gala 2026',
    category: 'Homecoming',
    summary: 'Registration is officially open for the milestone 50th University Homecoming! Reconnect with faculty, batchmates, and campus leadership.',
    date: 'Oct 16, 2026',
    readTime: '3 min read',
    badgeColor: '#7C3AED',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'ann-2',
    title: 'Fall 2026 University Career & Tech Internship Fair',
    category: 'Career',
    summary: '45+ partner firms including Google, Stripe, Microsoft, and leading national institutions are visiting campus for on-site hiring.',
    date: 'Sep 28, 2026',
    readTime: '2 min read',
    badgeColor: '#2563EB',
    imageUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'ann-3',
    title: 'Alumni Mentorship Fellowship Cohort 6 Applications Open',
    category: 'Announcement',
    summary: 'Exclusive 1-on-1 mentorship matching for pre-final & final year students with senior alumni executives in technology, finance, and health.',
    date: 'Aug 24, 2026',
    readTime: '4 min read',
    badgeColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80',
  }
];

